<Project Sdk="Aspire.AppHost.Sdk/13.5.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>ebd8427b-c0bb-467d-b8b9-aae27417ad88</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnionTypeExp.Server\UnionTypeExp.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Scalar.Aspire" />
  </ItemGroup>
</Project>
